
DROP TABLE IF EXISTS Pertinence ;

DROP TABLE IF EXISTS Categories_Jeu ;

DROP TABLE IF EXISTS Note ;

DROP TABLE IF EXISTS Commentaire ;

DROP TABLE IF EXISTS Jeu ;

DROP TABLE IF EXISTS Editeur;

DROP TABLE IF EXISTS Joueur ;

DROP TABLE IF EXISTS Categorie ;

DROP TABLE IF EXISTS Plateforme ; 

